"""Headed Playwright test for entity research → DataSift upload flow.

Uploads the entity test CSV generated by the E2E test, then keeps
browser open for manual inspection of entity columns/tags.

Usage:
    python test_entity_upload.py
"""

import asyncio
import logging
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "src"))

from dotenv import load_dotenv
load_dotenv()

from datasift_uploader import login, upload_csv

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)

CSV_PATH = "output/datasift_upload_DMs_2026-03-23_104301.csv"
LIST_NAME = "TN Public Notice 2026-03-23-entity-test - DMs"


async def main():
    from pathlib import Path

    csv_path = Path(CSV_PATH)
    if not csv_path.exists():
        logger.error("Test CSV not found: %s", CSV_PATH)
        return

    email = os.environ.get("DATASIFT_EMAIL", "")
    password = os.environ.get("DATASIFT_PASSWORD", "")

    if not email or not password:
        logger.error("DATASIFT_EMAIL and DATASIFT_PASSWORD must be set in .env")
        return

    from playwright.async_api import async_playwright

    logger.info("Starting headed Playwright browser...")
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=False)
        context = await browser.new_context(
            viewport={"width": 1280, "height": 720},
            user_agent=(
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/120.0.0.0 Safari/537.36"
            ),
        )
        page = await context.new_page()

        # Login
        logger.info("Logging in to DataSift...")
        logged_in = await login(page, email, password)
        if not logged_in:
            logger.error("Login failed!")
            await browser.close()
            return

        logger.info("Login successful! Current URL: %s", page.url)

        # Upload entity test CSV
        logger.info("=== UPLOADING ENTITY TEST CSV ===")
        logger.info("CSV: %s", CSV_PATH)
        logger.info("List: %s", LIST_NAME)

        result = await upload_csv(page, csv_path.resolve(), list_name=LIST_NAME)
        logger.info("Upload result: %s", result)

        if result.get("success"):
            logger.info("Upload successful! Check DataSift for:")
            logger.info("  - List: %s", LIST_NAME)
            logger.info("  - Entity tags: entity_owned, entity_researched")
            logger.info("  - Entity columns: Entity Type, Entity Contact, Entity Contact Role")
            logger.info("  - Notes: 'Entity Contact: Sherolyn Kennel (Executor)'")
        else:
            logger.error("Upload failed: %s", result)

        # Keep browser open for inspection
        logger.info("Browser will stay open for 60 seconds for inspection...")
        await page.wait_for_timeout(60000)

        await browser.close()

    logger.info("Done!")


if __name__ == "__main__":
    asyncio.run(main())
